"""add persona_memories table

Revision ID: 293ec65308da
Revises: 83e06002ef72
Create Date: 2026-03-24 10:48:18.731603
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '293ec65308da'
down_revision: Union[str, None] = '83e06002ef72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persona_memories',
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('memory_type', sa.String(length=20), nullable=False),
    sa.Column('content', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_persona_memories_actor_id'), 'persona_memories', ['actor_id'], unique=False)
    op.create_index(op.f('ix_persona_memories_target_id'), 'persona_memories', ['target_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_persona_memories_target_id'), table_name='persona_memories')
    op.drop_index(op.f('ix_persona_memories_actor_id'), table_name='persona_memories')
    op.drop_table('persona_memories')
    # ### end Alembic commands ###
