"""add keywords to posts and comments

Revision ID: 3b9d04548a21
Revises: f917e92d34ce
Create Date: 2026-03-24 12:42:03.842545
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3b9d04548a21'
down_revision: Union[str, None] = 'f917e92d34ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('keywords', sa.Text(), server_default='[]', nullable=False))
    op.add_column('posts', sa.Column('keywords', sa.Text(), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'keywords')
    op.drop_column('comments', 'keywords')
    # ### end Alembic commands ###
