"""add username and password_hash to users

Revision ID: 52630a12be95
Revises: 8ca15cf2526e
Create Date: 2026-03-23 14:31:52.672739
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '52630a12be95'
down_revision: Union[str, None] = '8ca15cf2526e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), server_default='', nullable=False))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
