"""add popular_posts queue table

Revision ID: 65126465f6ae
Revises: 52630a12be95
Create Date: 2026-03-23 15:10:01.944935
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '65126465f6ae'
down_revision: Union[str, None] = '52630a12be95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('popular_posts',
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('popularity_score', sa.Float(), nullable=False),
    sa.Column('promoted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_popular_posts_post_id'), 'popular_posts', ['post_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_popular_posts_post_id'), table_name='popular_posts')
    op.drop_table('popular_posts')
    # ### end Alembic commands ###
