"""add knowledge_edges table

Revision ID: 78912f479fa4
Revises: 3b9d04548a21
Create Date: 2026-03-24 14:46:29.100340
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '78912f479fa4'
down_revision: Union[str, None] = '3b9d04548a21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_edges',
    sa.Column('persona_id', sa.Uuid(), nullable=False),
    sa.Column('keyword_from', sa.String(length=50), nullable=False),
    sa.Column('keyword_to', sa.String(length=50), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('relation', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('persona_id', 'keyword_from', 'keyword_to', name='uq_knowledge_edge')
    )
    op.create_index(op.f('ix_knowledge_edges_persona_id'), 'knowledge_edges', ['persona_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_edges_persona_id'), table_name='knowledge_edges')
    op.drop_table('knowledge_edges')
    # ### end Alembic commands ###
