"""add persona_relationships table

Revision ID: 83e06002ef72
Revises: 8c30a2287a8d
Create Date: 2026-03-23 18:03:06.271692
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '83e06002ef72'
down_revision: Union[str, None] = '8c30a2287a8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persona_relationships',
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('interaction_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('like_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('dislike_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('sentiment_score', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('actor_id', 'target_id', name='uq_persona_rel_pair')
    )
    op.create_index(op.f('ix_persona_relationships_actor_id'), 'persona_relationships', ['actor_id'], unique=False)
    op.create_index(op.f('ix_persona_relationships_target_id'), 'persona_relationships', ['target_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_persona_relationships_target_id'), table_name='persona_relationships')
    op.drop_index(op.f('ix_persona_relationships_actor_id'), table_name='persona_relationships')
    op.drop_table('persona_relationships')
    # ### end Alembic commands ###
