"""add persona_states and follow sentiment fields

Revision ID: 8c30a2287a8d
Revises: 485122d2a1fe
Create Date: 2026-03-23 17:02:44.676875
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8c30a2287a8d'
down_revision: Union[str, None] = '485122d2a1fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persona_states',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('active_interests', sa.Text(), nullable=False),
    sa.Column('mood', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_persona_states_user_id'), 'persona_states', ['user_id'], unique=True)
    op.add_column('follows', sa.Column('interaction_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('follows', sa.Column('sentiment_score', sa.Float(), server_default='0.0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('follows', 'sentiment_score')
    op.drop_column('follows', 'interaction_count')
    op.drop_index(op.f('ix_persona_states_user_id'), table_name='persona_states')
    op.drop_table('persona_states')
    # ### end Alembic commands ###
