"""add post_metadata table and reduce post column lengths

Revision ID: 8ca15cf2526e
Revises: c3a1b2d3e4f5
Create Date: 2026-03-23 14:14:06.920369
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8ca15cf2526e'
down_revision: Union[str, None] = 'c3a1b2d3e4f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_metadata',
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('persona_nickname', sa.String(length=50), nullable=False),
    sa.Column('model_used', sa.String(length=50), nullable=False),
    sa.Column('template_tier', sa.String(length=20), nullable=False),
    sa.Column('rag_context_summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_metadata_post_id'), 'post_metadata', ['post_id'], unique=True)
    op.alter_column('posts', 'title',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.alter_column('posts', 'content',
               existing_type=sa.TEXT(),
               type_=sa.String(length=140),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'content',
               existing_type=sa.String(length=140),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('posts', 'title',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.drop_index(op.f('ix_post_metadata_post_id'), table_name='post_metadata')
    op.drop_table('post_metadata')
    # ### end Alembic commands ###
