"""add trending_keywords table

Revision ID: f917e92d34ce
Revises: 293ec65308da
Create Date: 2026-03-24 12:15:53.532163
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f917e92d34ce'
down_revision: Union[str, None] = '293ec65308da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trending_keywords',
    sa.Column('keyword', sa.String(length=50), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('promoted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trending_keywords_keyword'), 'trending_keywords', ['keyword'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trending_keywords_keyword'), table_name='trending_keywords')
    op.drop_table('trending_keywords')
    # ### end Alembic commands ###
